### ISSUE TITLE
Renaming the `constructor` method

### ISSUE THREAD

**Issue by nstarman** [GalacticDynamics/unxt#211]
While it's very explicit and closely follows the terminology in the Python data model it's just so verbose.

```python
x = Quantity.constructor(...)
```

Replacement options:

1. `make`: *pros*: explicit that it's making something. *cons*: maybe vague what it's making. Could be a MakeFile?
2. `new`: *pros*: it evokes `__new__`, to which it is similar. *cons*: same as make.
3. `create`: 🤷 meh
4. `from_`: *pros*: 1) it closely follows the classmethod constructor pattern 2) it's kinda similar to `dict.fromkeys`, and 3) it fits naturally into any bespoke constructors we add in the future, e.g `from_file` (which might call `jnp.load`). *cons*: ?

@adrn @jnibauer what are your thoughts on the above options / do you have any others?

Once we decide for `unxt` I'll propagate this up to `coordinax` and `galax`.

**Comment by nstarman** [comment]
@adrn @jnibauer the more I think about it the more I like `from_`. It's the closest we have to existing constructor patterns and it also makes it clear that we aren't making or creating the arguments, but making a new Quantity *from* the arguments.

**Comment by adrn** [comment]
This is updated
