### ISSUE TITLE
Custom unit conversion

### ISSUE THREAD

**Issue by vadmbertr** [GalacticDynamics/unxt#214]
Hi!

I work with physical quantities located on a spatial grid in latitude / longitude expressed in degrees. 
I would therefore like to be able to convert distances in meters (or km) into degrees of latitude or longitude and vice versa (using the haversine approximation).
Is this something “easily” achievable using unxt? Which approach would be preferable?

Thanks a lot!
Vadim

**Comment by nstarman** [comment]
@vadmbertr. Happy to help. If you are looking to manually convert between distances and delta-degrees then you can use the Haversine approximation (either form).

E.g. here's examples doing the delta angle -> distance.

```python
from unxt import Quantity
import quaxed.numpy as jnp

# d = \Delta \text{lat} \times 111.139
lat = Quantity(45, "deg")
delta_lat = Quantity(0.2, "rad")
d_lat = delta_lat * Quantity(111.139, "km/deg")

# d = \Delta \text{long} \times 111.319 \cdot \cos(\text{lat})
delta_lon = Quantity(0.3, "rad")
d_lon = delta_lat * Quantity(111.139, "km/deg") * jnp.cos(lat)

print(d_lat.to("km"), d_lon.to("km"), sep="\n")
# Quantity['length'](Array(1273.5592, dtype=float32, weak_type=True), unit='km')
# Quantity['length'](Array(900.5423, dtype=float32, weak_type=True), unit='km')
```

Or for the small angle approximation on a great circle

```
from unxt import ustrip

# Constants
R = Quantity(6371.0, "km")  # e.g. Earth's radius

# Inputs: delta_lat, delta_long, lat1, lat2
delta_lon = Quantity(..., "deg") # (or any angular units)
lat1 = Quantity(..., "deg")
lat2 = Quantity(..., "deg")

a = jnp.sin((lat2 - lat1) / 2) ** 2 + jnp.cos(lat1) * jnp.cos(lat2) * jnp.sin(delta_lon / 2) ** 2
c = 2 * ustrip("rad", jnp.arctan2(jnp.sqrt(a), jnp.sqrt(1 - a)))

d = R * c
print(d)
```

These can of course be turned into functions — e.g. ``haversine_approx(lat1, lat2, delta_lon, R)``.

**Comment by nstarman** [comment]
Please be aware that `unxt` is still in its `v0.X` series and its API is subject to change, e.g. see #211 for an impactful change to the convenience constructor method. That being said, The API I used here (direct construction of a `Quantity` and `ustrip`) are most likely very stable.

**Comment by vadmbertr** [comment]
Hi @nstarman, thanks for the reply.

Sorry, my question was a bit vague. 
I am interested in knowing if you have some advice on how (if possible) to "overload" the `to_unit` method such that converting between SI length units and custom latitude or longitude degrees units (how can I create those?) is accepted (as of course natively it is not possible to convert between length units and the existing degree unit for angles).

**Comment by nstarman** [comment]
Thanks for the clarification.
`unxt` uses `astropy.units` as the unit conversion backend. In astropy you can make unit equivalencies, enabling conversions between non-compatible dimensions or for non-multiplicative transforms, like Celsius to Fahrenheit.
See https://docs.astropy.org/en/stable/units/equivalencies.html.
If you define a new equivalency implementing the haversine approx, then yes you can do it with `Quantity.to`.
Note that `Quantity.to` does not accept an equivalency argument, you'll need to use [the context manager](https://docs.astropy.org/en/stable/units/equivalencies.html#id13)

**Comment by nstarman** [comment]
If you're interested to see an example in the (private) documentation, see https://github.com/GalacticDynamics/unxt/blob/a79d90304aba2cb484a87f240832e547d3a09cc2/src/unxt/_interop/unxt_interop_astropy/quantity.py#L287. That enables (and unit tests) the Celsius to Fahrenheit conversion via an equivalency context manager.

**Comment by vadmbertr** [comment]
Thanks a lot for the pointers!

Unfortunately, since I need an extra latitude parameter for my transformation function, I think I'll have to adopt the `ustrip` approach (or rebuild an equivalence every time I want to apply this conversion, which doesn't look very neat).

**Comment by nstarman** [comment]
Happy to help!
Is this Q answered?

**Comment by vadmbertr** [comment]
Yes, thanks a lot!
